### ISSUE TITLE
Confirm spell base AR and healing values

### ISSUE THREAD

**Issue by jerpdoesgames** [jerpdoesgames/EldenRingData#4]
Will need a test dummy with known defense/negation values.

I also want to confirm if the following are identical to Dark Souls 3:

- Weapon buffs still only scale with the Sorcery/Incantation scaling listed on the casting tool (Base Spell Buff) and aren't affected by Talismans, etc.
- Healing over time spells (Blessing's Boon, etc.) don't scale at all.

**Comment by jerpdoesgames** [comment]
Mostly just need healing/duration values now

**Comment by GavinRay97** [comment]
Let me know if you still need help with this/a second person

**Comment by jerpdoesgames** [comment]
Oh yeah, forgot to close this.  I successfully tested weapon buffs not gaining scaling outside of the primary stat (scholar's armament only with int, electrify armament only via faith, etc.).

The other values I just need to find time to plug in - turns out all of this stuff has been data mined:
https://docs.google.com/spreadsheets/d/1j4bpTbsnp5Xsgw9TP2xv6d8R4qk0ErpE9r_5LGIDraU/edit#gid=681223203

So most of what remains is in issue #1
